server:
  port: 8443
  ssl:
    key-alias: tomcat
    key-store: classpath:keystore.jks
    key-password: 123456
    key-store-password: 123456
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 5000ms
    database: 0
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1ms
        max-idle: 8
