spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    timeout: 5000ms
    database: 0
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1ms
        max-idle: 8

